config/routes.rb
Rails.application.routes.draw do
  get 'watch/search'

  resources :examples
  # get 'movie/index'
  # get 'movie/new'
  # get 'movie/show'
  # get 'movie/edit'
  # get 'movie/update'
  # get 'movie/delete'

  resources :movies
  resources :posts
  resources :favorite
  resources :mention
  resources :users

  # post 'movie_post/create'

  # get '/search_movie', to: 'welcome#search_movies', as: 'search_movies'
  # get '/clear_search', to: 'welcome#clear_search', as: 'clear_search'
  get '/flops', to: 'welcome#get_popular_flops', as: 'flops'
  get '/favorites', to: 'welcome#get_user_favorites', as: 'favorites'
  get '/recommendations', to: 'welcome#recommendations', as: 'recommendations'
  get 'watch', to: 'watch#search'
  post '/favorite', to: 'favorites#create'
  get 'search_movies', to: 'search_movies#index', as: :search_movies
  get 'clear_search',  to: 'search_movies#clear', as: :clear_search
  post '/recommendations', to: 'movies#add_recommendation', as: 'add_recommendation'

  # get 'password/edit'
  # get 'password/update'
  # get 'session/new'
  # get 'session/create'
  # get 'session/destroy'
  # get 'registration/new'
  # get 'registration/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'welcome#index'

  # sign in, sign up and sessions routes
  get     'sign_up',              to: 'registration#new'
  post    'sign_up',              to: 'registration#create'
  get     'sign_in',              to: 'session#new'
  post    'sign_in',              to: 'session#create', as: 'log_in'
  delete  'logout',               to: 'session#destroy'
  get     'password',             to: 'password#edit', as: 'edit_password'
  patch   'password',             to: 'password#update'
  get     'password/reset',       to: 'password_reset#new'
  post    'password/reset',       to: 'password_reset#create'
  get     'password/reset/edit',  to: 'password_reset#edit'
  patch   'password/reset/edit',  to: 'password_reset#update'

end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/example.rb
class Example < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :favoritable, polymorphic: true
  # belongs_to :movie
end

app/models/flop.rb
class Flop < Movie
end

app/models/mention.rb
class Mention < ApplicationRecord

  belongs_to :mentionable, polymorphic: true

  # belongs_to :post
  # belongs_to :user

  def create_mention(user_id)
    user = User.find_by(id: user_id)
    if user
      user.mentions.create(user_has_viewed: false)
      # user.mentions.create(mentionable_type: 'Comment', user_has_viewed: false)
    end
  end

end

app/models/movie.rb
class Movie < ApplicationRecord

  has_one :popular_flop
  has_many :posts, dependent: :destroy
  has_many :favorites, as: :favoritable
  has_many :favorited_users, through: :favorites, source: :user
  
  scope :search, ->(query) {
    return all if query.blank?
    where("title ILIKE ?", "%#{query}%")
  }

  # def self.search_movies query
  #   result = Movie.where("title LIKE '%#{query}%'")
  # end

  def favorited_by?(user)
    return false unless user
    favorites.any? { |f| f.user_id == user.id }
  end

end

app/models/popular_flop.rb
class PopularFlop < ApplicationRecord
  has_many :users
  has_one :movie

  def self.popular_flops
    @flop_ids = PopularFlop.connection.select_all("SELECT movie_id, COUNT(movie_id) flop_count FROM popular_flops GROUP BY movie_id ORDER BY movie_id ASC").to_a.map{ |x| x["movie_id"] }
    # @popular_flops = Movie.connection.select_all("SELECT * FROM movies WHERE id IN (#{@flop_ids.join(',')})").rows
    @popular_flops = Movie.find(@flop_ids)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  has_many :replies, class_name: :Post, foreign_key: :reply_id
  has_many :favorites, as: :favoritable
  # belongs_to :comment, class_name: :Post

  has_many :mentions, as: :mentionable

  after_create :create_mention

   private

    def create_mention()
      user = User.find_by(handle: self.handle.strip)
      if user
        user.mentions.create(user_has_viewed: false)
      end

      self.mentions.create({user_id: user.id})
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :popular_flops
    has_many :comments, as: :commentable, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :movie_posts

    has_many :favorite_movies,
         -> { where(favorites: { favoritable_type: "Movie" }) },
         through: :favorites,
         source: :favoritable,
         source_type: "Movie"

    has_many :mentions, as: :mentionable

    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }

    def find_my_mentions
      mentions = self.mentions.where(user_has_viewed: false)
      return mentions
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  require 'uri'
  require 'net/http'

  def index
  end

  def new
    @content_ratings = Movie.distinct.pluck(:content_rating)
    get_users_mentions
  end

  def create
    binding.pry
  end

  def show
    @post_struc = {}

    @movie = Movie.find_by(id: params[:id])
    @posts = @movie.posts.select{ |post| post.reply_id == 0 }

    # base case: when replies returns an empty array
    # {post: post, replies: replies[ {reply: reply, replies: replies[]}]}

    # @posts.each do |post|
    #   unless post.replies.empty?
    #     @post_struc << {post: post, replies: get_replies(post)}
    #   else 
    #     @post_struc << {post: post, replies: nil}
    #   end
    #   #get_replies(post)
    # end

    # binding.pry

    url = URI("https://moviesminidatabase.p.rapidapi.com/movie/id/#{@movie.imdb_id}/")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true

    request = Net::HTTP::Get.new(url)
    request["X-RapidAPI-Key"] = 'b626dd3aecmsh32f2180eee602fep10500cjsndf563d673d38'
    request["X-RapidAPI-Host"] = 'moviesminidatabase.p.rapidapi.com'

    response = http.request(request)

    @movie_stuff = JSON.parse(response.body)["results"] ? JSON.parse(response.body)["results"] : nil
    # binding.pry
  end

  def get_replies(post)
    # binding.pry
    # until post.replies.empty? # post has replies
      # @posts_struc = {post: post, replies: post.replies}
      # does the reply have other replies
      # get_replies post
    # end

    return post.replies
  end

  def edit
  end

  def update
  end

  def delete
  end

  # add user recommended movie
  def add_recommendation
    binding.pry
    recommendation = Current.user.recommendations.new(movie_id: params[:movie_id], reason: params[:reason])
    recommendation.assign_attributes(recommendation_params)
    if recommendation.save
      
    end
  end
    private

    def recommendation_params
      params.require(:movie).permit(:title, :year, :content_rating, :plot)
    end
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/favorite_helper.rb
module FavoriteHelper
end

app/helpers/mention_helper.rb
module MentionHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/movie_post_helper.rb
module MoviePostHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/watch_helper.rb
module WatchHelper
  private

  def normalize_results(raw)
    raw.map do |item|
      OpenStruct.new(
        title: item["title"],
        year: item["releaseYear"],
        overview: item["overview"],
        streaming_services: extract_services(item)
      )
      end
  end

  def extract_services(result)
  # If streamingInfo exists, convert keys to readable sources
  return [] unless item["streamingInfo"].is_a?(Hash)

  item["streamingInfo"].keys
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/movies/_comment_section.html.erb
    <%= hidden_field_tag  'movie_id', @movie.id %>
    <% @posts.each do |post| %> 
      <div class="comment-container" id="comment_<%= post.id %>">
          <div class="comment-header">
            <div class="comment-title">
              <%= post.title %> -- <%= post.created_at %>
            </div>
          </div>
          <div class="comment">
            <%= sanitize post.body %>
          </div>
          <div data-controller="post" 
            data-action="click->post#newPost" 
            data-post-comment-type-param="reply" 
            data-post-post-id-param="<%= post.id %>" 
            class="comment-save-btn" >Reply</div>
      </div>
      <div style="clear: both;"></div>
      <% unless post.replies.empty? %>
        <% post.replies.each do |reply| %>
          <div class="reply-container" id="comment_<%= reply.id %>">
            <div class="reply-header">
              <div class="comment-title">
                <%= reply.title %> to <%= post.title %> by: -- <%= reply.user.email %> -- <%= reply.created_at %>
              </div>
            </div>
            <div class="comment">
              <%= sanitize reply.body %>
            </div>
            <div data-controller="post" 
              data-action="click->post#newPost" 
              data-post-comment-type-param="reply"
              data-post-post-parent-id-param="<%= post.id %>"
              data-post-post-id-param="<%= reply.id %>" 
              class="reply-save-btn" >Reply
            </div>
          </div>
          <div style="clear: both;"></div>
          <% unless reply.replies.empty? %>
            <% reply.replies.each do |r|%>
              <div class="reply-container" id="comment_<%= r.id %>">
                <div class="reply-header">
                  <div class="comment-title">
                    <%= r.title %> to <%= reply.title %> by: -- <%= r.user.email %> -- <%= r.created_at %>
                  </div>
                </div>
                <div class="comment">
                  <%= r.body %>
                </div>
                <div data-controller="post" 
                  data-action="click->post#newPost" 
                  data-post-comment-type-param="reply"
                  data-post-post-parent-id-param="<%= reply.id %>"
                  data-post-post-id-param="<%= r.id %>" 
                  class="reply-save-btn" >Reply
                </div>
              </div>
              <div style="clear: both;"></div>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>

app/views/movies/_current_favorites.html.erb
all out favorites

app/views/movies/_favorite_button.html.erb
<%#= turbo_frame_tag dom_id(movie, :favorite) do %>
  <button data-controller="favorites" 
  data-action="click->favorites#addToFavorites" 
  data-favorites-movie-id-value="<%= movie.id %>" 
  data-favorites-user-id-value="<%= Current.user.id %>" 
  data-favorites-fav-type-value="movie" 
  class="favorite-btn <%= 'active' if movie.favorited_by?(Current.user) %>">
  </button>
<%# end %>

app/views/movies/_movie_table_display.html.erb
<%  @user = Current.user %>
<div id="my_bonks" class="city">
  <section class="display-header-container">
    <div class="display-header-grid">
      <div class="display-title">Title</div>
      <div class="display-year">Year</div>
      <div class="display-est-budget">Estimated Budget</div>
      <div class="display-gross">Worldwide Gross</div>
      <div class="display-details">Details</div>
      <div class="display-fav">&nbsp</div>
    </div>
  </section>
  <section class="movie-display-sheet" id="postsList">
    <% movies&.each do |movie| %>
    <%= turbo_frame_tag dom_id(movie) do %>
    <details class="movie-display-row" data-controller="movie_listing_display" data-movie_listing_display-title-value="<%= movie.title %>">
      <!-- " accordian" add detalis controller with data-action that listtens for open event -->
      <summary>
        <%# binding.pry%>
        <div class="movie-line-item">
          <div class="movie-line-item-title"><%= movie.title %></div>
          <div class="movie-line-item-year"><%= movie.year_released %></div>
          <div class="movie-line-item-est-budget"><%= movie.budget %></div>
          <div class="movie-line-item-gross"><%= movie.worldwide_gross %></div>
          <div class="movie-line-item-details">
            <% if movie.imdb_id %>
            <%= link_to movie_path(movie), data: { turbo: "false" }, class: 'film-link' do %>
            <%= fa_icon 'film', class: 'icon'%>
            <% end %>
            <% end %>
          </div>
          <% if @user %>
            <div class="movie-line-item-fav" data-controller="favorites" data-action="click->favorites#addToFavorites" data-favorites-movie-id-param="<%= movie.id %>" data-favorites-user-id-param="<%= Current.user.id %>" data-favorites-fav-type-param="movie">
              <% if (movie.favorites.exists? user_id: Current.user.id ) %>
              <div class="favorite-movie">
                <%= fa_icon 'thumbs-up', class: 'icon'%>
              </div>
              <% else %>
              <div class="favorite-thumb">
                <%= fa_icon 'thumbs-up', class: 'icon'%>
              </div>
              <% end %>
              <%#= render partial: "movies/favorite_button", locals: { movie: movie.favoritable } %>
            </div>
          <% end %>
      </summary>
      <%#= render "movies/watch_results", results: @result %>
      <div data-movie_listing_display-target="results"></div>
    </details>
    <% end %>
    <% end %>
  </section>
</div>

app/views/movies/_popular_flops.html.erb
<% @popular_flops.each do |flop|%>
<div class="popular-flops-grid">
  <div class="popular-flops-likes-count">
    <%= Favorite.where(favoritable_id: flop.favoritable.id).count %><%#= fa_icon 'thumbs-up', class: 'icon'%>
  </div>
  <div class="popular-flops-title">
    <span class="tooltip" data-tooltip="<%= flop.favoritable.title %>">
      <%= flop.favoritable.title.truncate(25, omission: '...') %>
    </span>
  </div>
</div>
<% end %>

app/views/movies/_tabbed_content.html.erb
<turbo-frame id="tab-content">
<%# binding.pry %>
  <% if movies.present? && movies != 'recommendations' %>
  <%= render partial: "movies/movie_table_display", locals: { movies: movies } %>
  <% else %>
  <%# binding.pry %>
  <%= render partial: "movies/recommendation" %>
  <% end %>
</turbo-frame>

app/views/movies/_watch_results.html.erb
<% if results.present? %>
<% results.each do |result| %>
<% if result.streaming_services.present? %>
<% result.streaming_services.each do |service| %>
<div class="streaming-list">
  <div class="streaming-service">
    <%= service[:service_name] %>
  </div>
  <div class="service-type">
    <%= service[:type].capitalize %>
  </div>
  <div class="service-price">
    <% if service[:price].present? %>
    – <%= service[:price] %>
    <% end %>
  </div>
  <div class="service-link">
    <%= link_to service[:link], target: "_blank" do %>
    <%= fa_icon 'link', class: 'icon'%>
    <% end %>
  </div>
</div>
<% end %>
<% end %>
<% end %>
<% else %>
<p>No results found.</p>
<% end %>

app/views/movies/delete.html.erb
<h1>Movie#delete</h1>
<p>Find me in app/views/movie/delete.html.erb</p>

app/views/movies/edit.html.erb
<h1>Movie#edit</h1>
<p>Find me in app/views/movie/edit.html.erb</p>

app/views/movies/get_popular_flops.js.erb
$('.items-container').html("<%= j (render partial: 'movie_table_display') %>")

app/views/movies/index.html.erb
<h1>Movie#index</h1>
<p>Find me in app/views/movie/index.html.erb</p>

app/views/movies/new.html.erb
<div class="welcome-grid">
  <section class="welcome-grid-title">
    <% if Current.user %>
      <section class="header-grid">
        <div class="welcome-search">
          <%= render 'movies/search_movies' %>
        </div>
        <div class="welcome-recommendation">
          <%= button_to 'Save Recommendation', movies_path, method: :post, class: 'recommendation-btn' %>
        </div>
      </section>
    <% end %>
  </section>
  <section class="welcome-main">
    <%= form_with model: @movie do |form| %>
      <div class="movie-form">
        <div class="movie-form-title">
          <div class="form-group">
            <div class="form-caption">Movie Title</div>
            <%= form.text_field :title, placeholder: 'Movie Title', class: 'movie-form-input' %>
          </div>
        </div>
        <div class="movie-form-genre">
          <div class="form-group">
            <div class="form-caption">Movie Rating</div>
            <%= form.select :content_rating, @content_ratings %>
            <%#= form.text_field :Genre, placeholder: 'Movie Genre', class: 'movie-form-input' %>
          </div>
        </div>
        <div class="movie-form-year">
          <div class="form-group">
            <div class="form-caption">Movie Year</div>
            <%= form.text_field :year_released, placeholder: 'Movie Year', class: 'movie-form-input' %>
          </div>
        </div>
        <div class="movie-form-plot">
          <div class="form-group">
            <div class="form-caption">Movie Plot</div>
            <%= form.text_area :plot, placeholder: 'Movie Plot', class: 'movie-form-input' %>
          </div>
        </div>
        <div class="movie-form-trailer">
          <div class="form-group">
            <div class="form-caption">Movie Trailer</div>
            <%= form.text_field :trailer, placeholder: 'Movie Trailer', class: 'movie-form-input' %>
          </div>
        </div>
        <%= form.submit 'Save recommendation', class: 'recommendation-btn movie-form-submit' %>
      </div>
    <% end %>
  </section>
  <section class="user_info">
    <%= render 'shared/user_panel' %>
  </section>
</div>

app/views/movies/show.html.erb
<div class="container main-grid">
  <%
=begin%>
  create a tabbed view: one tab for current user's favorites
  and another tab for the user to see a list of other movies
  <%
=end%>
  <div class="container-left">
    <div class="poster">
      <% unless @movie_stuff["banner"].blank? %>
      <%= image_tag @movie_stuff["banner"] %>
      <% end %>
    </div>
  </div>
  <div class="container-right">
    <div class="video">
      <iframe class="video-frame" title="<%= @movie_stuff['title'] %>" src="<%= @movie_stuff['trailer'] %>">
      </iframe>
    </div>
    <div class="movie-info">
      <div class="movie-info-grid">
        <!-- Probably need to look into a grid layout for this -->
        <div class="movie-title"><%= @movie_stuff['title'] %></div>
        <div class="rating"><%= @movie_stuff['content_rating'] %></div>
        <div class="year"><%= @movie_stuff['year'] %></div>
        <div class="movie-desc"><%= @movie_stuff["description"] %></div>
      </div>
    </div>
  </div>
  <div class="posts-dashboard" data-controller="post">
    <div id="add-comments-btn" class="add-post" data-post-comment-type-param="submit" data-post-movie-id-param="<%= @movie.id %>" data-action="click->post#newPost"><%= fa_icon 'plus' %></div>
    <span style="float: right; margin-right: 20px; padding-top: 5px;">Comments section...</span>
  </div>
  <div id="comments-container" class="container-comments">
    <div id="comments-field" class="comments-field"></div>
    <%= render 'comment_section' %>
    <%
=begin%>
    <%= hidden_field_tag  'movie_id', @movie.id %>
    <% @posts.each do |post| %>
    <div class="comment-container" id="comment_<%= post.id %>">
      <div class="comment-header">
        <div class="comment-title">
          <%= post.title %> -- <%= post.created_at %>
        </div>
      </div>
      <div class="comment">
        <%= post.body %>
      </div>
      <div data-controller="post" data-action="click->post#newPost" data-post-comment-type-param="reply" data-post-post-id-param="<%= post.id %>" class="comment-save-btn">Reply</div>
    </div>
    <div style="clear: both;"></div>
    <% unless post.replies.empty? %>
    <% post.replies.each do |reply| %>
    <div class="reply-container" id="comment_<%= reply.id %>">
      <div class="reply-header">
        <div class="comment-title">
          <%= reply.title %> to <%= post.title %> by: -- <%= reply.user.email %> -- <%= reply.created_at %>
        </div>
      </div>
      <div class="comment">
        <%= reply.body %>
      </div>
      <div data-controller="post" data-action="click->post#newPost" data-post-comment-type-param="reply" data-post-post-parent-id-param="<%= post.id %>" data-post-post-id-param="<%= reply.id %>" class="reply-save-btn">Reply
      </div>
    </div>
    <div style="clear: both;"></div>
    <% unless reply.replies.empty? %>
    <% reply.replies.each do |r|%>
    <div class="reply-container" id="comment_<%= r.id %>">
      <div class="reply-header">
        <div class="comment-title">
          <%= r.title %> to <%= reply.title %> by: -- <%= r.user.email %> -- <%= r.created_at %>
        </div>
      </div>
      <div class="comment">
        <%= r.body %>
      </div>
      <div data-controller="post" data-action="click->post#newPost" data-post-comment-type-param="reply" data-post-post-parent-id-param="<%= reply.id %>" data-post-post-id-param="<%= r.id %>" class="reply-save-btn">Reply
      </div>
    </div>
    <div style="clear: both;"></div>
    <% end %>
    <% end %>
    <% end %>
    <% end %>
    <% end %>
    <%
=end%>
  </div>
</div>

app/views/movies/update.html.erb
<h1>Movie#update</h1>
<p>Find me in app/views/movie/update.html.erb</p>