config/routes.rb
Rails.application.routes.draw do
  get 'watch/search'

  resources :examples
  # get 'movie/index'
  # get 'movie/new'
  # get 'movie/show'
  # get 'movie/edit'
  # get 'movie/update'
  # get 'movie/delete'

  resources :movies
  resources :posts
  resources :favorite
  resources :mention
  resources :users

  # post 'movie_post/create'

  # get '/search_movie', to: 'welcome#search_movies', as: 'search_movies'
  # get '/clear_search', to: 'welcome#clear_search', as: 'clear_search'
  get '/flops', to: 'welcome#get_popular_flops', as: 'flops'
  get '/favorites', to: 'welcome#get_user_favorites', as: 'favorites'
  get '/recommendations', to: 'welcome#recommendations', as: 'recommendations'
  get 'watch', to: 'watch#search'
  post '/favorite', to: 'favorites#create'
  get 'search_movies', to: 'search_movies#index', as: :search_movies
  get 'clear_search',  to: 'search_movies#clear', as: :clear_search
  post '/recommendations', to: 'movies#add_recommendation', as: 'add_recommendation'

  # get 'password/edit'
  # get 'password/update'
  # get 'session/new'
  # get 'session/create'
  # get 'session/destroy'
  # get 'registration/new'
  # get 'registration/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'welcome#index'

  # sign in, sign up and sessions routes
  get     'sign_up',              to: 'registration#new'
  post    'sign_up',              to: 'registration#create'
  get     'sign_in',              to: 'session#new'
  post    'sign_in',              to: 'session#create', as: 'log_in'
  delete  'logout',               to: 'session#destroy'
  get     'password',             to: 'password#edit', as: 'edit_password'
  patch   'password',             to: 'password#update'
  get     'password/reset',       to: 'password_reset#new'
  post    'password/reset',       to: 'password_reset#create'
  get     'password/reset/edit',  to: 'password_reset#edit'
  patch   'password/reset/edit',  to: 'password_reset#update'

end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/example.rb
class Example < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :favoritable, polymorphic: true
  # belongs_to :movie
end

app/models/flop.rb
class Flop < Movie
end

app/models/mention.rb
class Mention < ApplicationRecord

  belongs_to :mentionable, polymorphic: true

  # belongs_to :post
  # belongs_to :user

  def create_mention(user_id)
    user = User.find_by(id: user_id)
    if user
      user.mentions.create(user_has_viewed: false)
      # user.mentions.create(mentionable_type: 'Comment', user_has_viewed: false)
    end
  end

end

app/models/movie.rb
class Movie < ApplicationRecord

  has_one :popular_flop
  has_many :posts, dependent: :destroy
  has_many :favorites, as: :favoritable
  has_many :favorited_users, through: :favorites, source: :user
  
  scope :search, ->(query) {
    return all if query.blank?
    where("title ILIKE ?", "%#{query}%")
  }

  # def self.search_movies query
  #   result = Movie.where("title LIKE '%#{query}%'")
  # end

  def favorited_by?(user)
    return false unless user
    favorites.any? { |f| f.user_id == user.id }
  end

end

app/models/popular_flop.rb
class PopularFlop < ApplicationRecord
  has_many :users
  has_one :movie

  def self.popular_flops
    @flop_ids = PopularFlop.connection.select_all("SELECT movie_id, COUNT(movie_id) flop_count FROM popular_flops GROUP BY movie_id ORDER BY movie_id ASC").to_a.map{ |x| x["movie_id"] }
    # @popular_flops = Movie.connection.select_all("SELECT * FROM movies WHERE id IN (#{@flop_ids.join(',')})").rows
    @popular_flops = Movie.find(@flop_ids)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  has_many :replies, class_name: :Post, foreign_key: :reply_id
  has_many :favorites, as: :favoritable
  # belongs_to :comment, class_name: :Post

  has_many :mentions, as: :mentionable

  after_create :create_mention

   private

    def create_mention()
      user = User.find_by(handle: self.handle.strip)
      if user
        user.mentions.create(user_has_viewed: false)
      end

      self.mentions.create({user_id: user.id})
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :popular_flops
    has_many :comments, as: :commentable, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :movie_posts

    has_many :favorite_movies,
         -> { where(favorites: { favoritable_type: "Movie" }) },
         through: :favorites,
         source: :favoritable,
         source_type: "Movie"

    has_many :mentions, as: :mentionable

    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }

    def find_my_mentions
      mentions = self.mentions.where(user_has_viewed: false)
      return mentions
    end
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/favorite_helper.rb
module FavoriteHelper
end

app/helpers/mention_helper.rb
module MentionHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/movie_post_helper.rb
module MoviePostHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/watch_helper.rb
module WatchHelper
  private

  def normalize_results(raw)
    raw.map do |item|
      OpenStruct.new(
        title: item["title"],
        year: item["releaseYear"],
        overview: item["overview"],
        streaming_services: extract_services(item)
      )
      end
  end

  def extract_services(result)
  # If streamingInfo exists, convert keys to readable sources
  return [] unless item["streamingInfo"].is_a?(Hash)

  item["streamingInfo"].keys
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auth</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="main-nav">
      <section class="main-logo">
        <%= link_to root_path do %>
          <%= image_tag 'Logo.png', class: 'resize-image'%>
        <% end %>
      </section>
      <section class="logged-in-user">

      </section>
      <section class="main-sign-up">
        <% if Current.user %>
          <%= button_to 'Update Password', edit_password_path, method: :get, method: :get, class: 'links links-right' %>
        <% else %>
          <%= button_to 'Sign Up', sign_up_path, method: :get, class: 'links links-right' %>
        <% end %>
      </section>
      <section class="main-login">
        <% if Current.user %>
          <%= button_to 'Logout', logout_path, method: :delete, class: 'links links-left' %>
        <% else %>
          <%= button_to 'Login', sign_in_path, method: :get, class: 'links links-left' %>
        <% end %>
      </section>
    </div>
    <%= yield %>
  </body>
</html>

app/views/shared/_user_panel.html.erb
<% if Current.user %>
  <div class="logged-in-user-title">
    <%= Current.user.email %>
  </div>
  <div id="mentioned-posts-container">
    <% if @posts %>
      <div class="mention-header">You've been mentioned in these posts</div>
      <div class="arrow-down"></div>
      <div class="arrow-down-top"></div>
      <br/>
    <% end %>
    <ul id="mentioned-posts">
      <% @posts.each do |post| %>
        <li>
          <%= fa_icon 'comments' %>
          <a href="/movies/<%= post.movie.id %>/#comment_<%= post.id %>"><%= post.title %></a>
        </li>
      <% end %>
    </ul>
  </div>
<% else %>
  <p class="alert"><%= alert %></p>
<% end %>